# Generated by Django 3.2.5 on 2022-04-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugTracker', '0002_alter_customuser_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='issue_type',
            field=models.CharField(blank=True, choices=[('i', 'Improve'), ('t', 'Task'), ('b', 'Bug'), ('r', 'Request')], max_length=1),
        ),
        migrations.AddField(
            model_name='issue',
            name='priority',
            field=models.CharField(blank=True, choices=[('h', 'High'), ('m', 'Middle'), ('l', 'Low')], max_length=1),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(blank=True, choices=[('o', 'Open'), ('p', 'In Progress'), ('r', 'Resolved')], default='o', max_length=1),
        ),
    ]
