# Generated by Django 4.1 on 2023-01-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugTracker', '0002_alter_issue_priority_alter_issue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.IntegerField(blank=True, choices=[(3, 'High'), (2, 'Middle'), (1, 'Low')]),
        ),
    ]
