# Generated by Django 3.2.5 on 2022-04-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugTracker', '0003_auto_20220417_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
